name: kitchen-tests

on: [push, workflow_dispatch]

jobs:
  all:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: ghcr.io/brownuniversity/kitchen-terraform:1.0.0

    steps:
    - uses: actions/checkout@v1
    - name: Create Credential File
      run: |
        echo "$GCP_CREDENTIAL_JSON" | base64 -d > /tmp/credentials.json
      env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
    - name: Run Kitchen
      run: kitchen test
      env:
        TF_VAR_billing_account: ${{ secrets.GCP_BURWOOD_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_CCV_CI_FOLDER_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json


