name: terraform-tests

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:  
    branches:
      - 'main'

jobs:
  terraform-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Credential File
      run: |
        echo "$GCP_CREDENTIAL_JSON" | base64 -d > /tmp/credentials.json
      env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CI_CREDENTIAL_JSON}}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.3 # Get the latest from: https://releases.hashicorp.com/terraform/
    - name: Run terraform tests
      run: |
        terraform init
        terraform test
      env:
        TF_VAR_billing_account: ${{ secrets.GCP_BURWOOD_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_CCV_CI_FOLDER_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json


